#!/bin/sh

[ -r ./conf ] && . ./conf

: ${SERVER:=popcorn.plan10.org}
: ${PORT:=8001}

chpst -u _popcorn:_popcorn popcorn --server $SERVER --port $PORT
exec chpst -u _popcorn:_popcorn snooze popcorn --server $SERVER --port $PORT
