#!/bin/bash

build() {
    for bin in /usr/bin/pkginst-*; do
        add_binary "$bin"
    done

    for key in /var/db/pkginst/keys/*; do
        add_file "$key"
    done

    for conf in /usr/share/pkginst.d/*; do
        add_file "$conf"
    done
}

help() {
    cat <<HELPEOF
This hook will add pkginst to recover broken plan10 installations.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
