# Cross build profile for ARMv8.

PKGINST_TARGET_MACHINE="aarch64-musl"
PKGINST_TARGET_QEMU_MACHINE="aarch64"
PKGINST_CROSS_TRIPLET="aarch64-linux-musl"
PKGINST_CROSS_CFLAGS="-march=armv8-a"
PKGINST_CROSS_CXXFLAGS="$PKGINST_CROSS_CFLAGS"
PKGINST_CROSS_FFLAGS=""
PKGINST_CROSS_RUSTFLAGS="--sysroot=${PKGINST_CROSS_BASE}/usr"
PKGINST_CROSS_RUST_TARGET="aarch64-unknown-linux-musl"
