# Cross build profile for i686 and Musl libc.

PKGINST_TARGET_MACHINE="i686-musl"
PKGINST_TARGET_QEMU_MACHINE="i386"
PKGINST_CROSS_TRIPLET="i686-linux-musl"
PKGINST_CROSS_CFLAGS="-march=i686"
PKGINST_CROSS_CXXFLAGS="$PKGINST_CROSS_CFLAGS"
PKGINST_CROSS_FFLAGS=""
PKGINST_CROSS_RUSTFLAGS="--sysroot=${PKGINST_CROSS_BASE}/usr"
PKGINST_CROSS_RUST_TARGET="i686-unknown-linux-musl"
