# Cross build profile for MIPS32 LE soft float.

PKGINST_TARGET_MACHINE="mipsel-musl"
PKGINST_TARGET_QEMU_MACHINE="mipsel"
PKGINST_CROSS_TRIPLET="mipsel-linux-musl"
PKGINST_CROSS_CFLAGS="-mtune=mips32r2 -mabi=32 -msoft-float"
PKGINST_CROSS_CXXFLAGS="$PKGINST_CROSS_CFLAGS"
PKGINST_CROSS_FFLAGS=""
PKGINST_CROSS_RUSTFLAGS="--sysroot=${PKGINST_CROSS_BASE}/usr"
PKGINST_CROSS_RUST_TARGET="mipsel-unknown-linux-musl"
