PKGINST_TARGET_CFLAGS="-march=armv6 -mfpu=vfp -mfloat-abi=hard"
PKGINST_TARGET_CXXFLAGS="$PKGINST_TARGET_CFLAGS"
PKGINST_TARGET_FFLAGS=""
PKGINST_TRIPLET="armv6l-unknown-linux-gnueabihf"
PKGINST_RUST_TARGET="arm-unknown-linux-gnueabihf"
