PKGINST_TARGET_CFLAGS="-mcpu=powerpc -mno-altivec -mtune=G4 -mlong-double-64"
PKGINST_TARGET_CXXFLAGS="$PKGINST_TARGET_CFLAGS"
PKGINST_TARGET_FFLAGS=""
PKGINST_TRIPLET="powerpc-linux-musl"
PKGINST_RUST_TARGET="powerpc-unknown-linux-musl"
