#!/bin/sh
# Use a modules directory which doesn't exist so we don't load random things
# which may then get deleted (or their dependencies) and potentially segfault
export GIO_MODULE_DIR=${PKGINST_CROSS_BASE}/gio/modules-dummy

/usr/bin/qemu-${PKGINST_TARGET_QEMU_MACHINE}-static ${GIR_EXTRA_OPTIONS} \
			-L ${PKGINST_CROSS_BASE} \
			-E LD_LIBRARY_PATH="${PKGINST_CROSS_BASE}/usr/lib:.libs:${GIR_EXTRA_LIBS_PATH}" \
			"$@"
